use std::env;
use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();
    write_bundled_secrets();
}

fn write_bundled_secrets() {
    println!("cargo:rerun-if-env-changed=EMBEDDING_API_KEY");

    let secrets_path = Path::new(".secrets/embedding_api_key");
    println!("cargo:rerun-if-changed={}", secrets_path.display());

    let api_key = env::var("EMBEDDING_API_KEY")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .or_else(|| read_secret_file(secrets_path));

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("bundled_secrets.rs");

    let body = match api_key {
        Some(key) => format!(
            "// @generated by build.rs — do not edit\n\
             pub const EMBEDDING_API_KEY: Option<&'static str> = Some({key:?});\n"
        ),
        None => "// @generated by build.rs — do not edit\n\
                 pub const EMBEDDING_API_KEY: Option<&'static str> = None;\n"
            .to_string(),
    };

    fs::write(&out_path, body).expect("failed to write bundled_secrets.rs");
}

fn read_secret_file(path: &Path) -> Option<String> {
    let text = fs::read_to_string(path).ok()?;
    let trimmed = text.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}
