/** Stable action ids used by the TopBar menu and wired in App / TopBar. */
export type MenuActionId =
  | "file.openFolder"
  | "file.cloneRepo"
  | "file.save"
  | "file.closeProject"
  | "file.exit"
  | "edit.undo"
  | "edit.redo"
  | "view.toggleSidebar"
  | "view.toggleRight"
  | "view.toggleBottom"
  | "nav.goBack"
  | "nav.goForward"
  | "git.toggleCommit"
  | "git.createBranch"
  | "git.cloneRepo"
  | "git.pull"
  | "git.push"
  | "tools.settings"
  | "tools.toolLog"
  | "tools.plans"
  | "help.about"
  | "help.docs"
  | "help.feedback"
  | "help.updates";
